apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - kabana-knative.yaml
images:
  - name: ghcr.io/kabana-bbq/kabana
    newTag: sha-af7a93a
    newName: ghcr.io/kabana-bbq/kabana
